# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serviceapp', '0003_delete_advertisers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisers', models.CharField(max_length=100)),
            ],
        ),
    ]
